syntax = "proto3";

package src.protos.user;

import "google/protobuf/timestamp.proto";

service UserProfileService {
  rpc GetProfileById (GetProfileRequestById) returns (UserProfile);
  rpc GetProfileByEmail (GetProfileRequestByEmail) returns (UserProfile);
  rpc UpdateProfile (UpdateProfileRequest) returns (UpdateProfileResponse);
  rpc CreateProfile (CreateProfileRequest) returns (UserProfile);
  rpc DeleteProfile (DeleteProfileRequest) returns (DeleteProfileResponse);
  rpc GetUserAuthData (GetUserAuthRequest) returns (UserAuthData);

}
message GetUserAuthRequest {
  string email = 1;
}

message UserAuthData {
  int64 user_id = 1;
  string password_hash = 2; 
  repeated UserRole roles = 3;
}
message DeleteProfileRequest {
  int64 user_id = 1;
}
message DeleteProfileResponse {
  bool success = 1;
  string message = 2;
}
message GetProfileRequestByEmail {
  string email = 1;
}

message CreateProfileRequest {
  int64 user_id = 1; 
  string full_name = 2;
  string email = 3;
  string phone = 4;
  string password_hash = 5;
  repeated UserRole roles = 6;
}

message GetProfileRequestById {
  int64 user_id = 1;
}

message GetProfileResponse {
  int64 user_id = 1;
  string full_name = 2;
  string email = 3;
  string phone = 4;
  string avatar_url = 5;
  bool is_verified = 6;
  google.protobuf.Timestamp registered_at = 7;
  UserRole role = 8;
}

message UpdateProfileRequest {
  int64 user_id = 1;
  string full_name = 2;
  string blood_type = 3;
  string avatar_url = 4;
}

message UpdateProfileResponse {
  bool success = 1;
  string message = 2;
}

message UserProfile {
  int64 user_id = 1;
  string name = 2;
  string email = 3;
  string blood_type = 4;
  bool is_verified = 5;
  int32 total_donations = 6;
  google.protobuf.Timestamp last_donation_at = 7;
  repeated UserRole roles = 8;
  bool is_active = 9;
  bool is_banned = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 12;
  string avatar_url = 13;
  string phone = 14;
  int32 lives_saved_count = 15;
  string donor_status = 16;
  bool has_donor_book = 17;
  bool test_is_done = 18;
  google.protobuf.Timestamp birth_date = 19;
}

enum UserRole {
  UNKNOWN = 0;
  DONOR = 1;
  DOCTOR = 2;
  ADMIN = 3;
}