services:
  user-profile:
    build:
      context: .
      dockerfile: ./services/user-profile/Dockerfile
    container_name: user-profile
    depends_on:
      - user-profile-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@user_profile_db:5432/user_profile_db
      - PYTHONPATH=/app/service/src
    ports:
      - "5001:50051"
    networks:
      - user-profile_net
      - gateway_net
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 5s
      timeout: 3s
      retries: 5
    platform: linux/amd64

  user-profile-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_profile_db
    volumes:
      - user-profile-data:/var/lib/postgresql/data
    networks:
      - user-profile_net
    ports:
      - "5433:5432"

  grpc-sandbox:
    build:
      context: .
      dockerfile: ./services/grpc-sandbox/Dockerfile
    container_name: grpc-sandbox
    depends_on:
       user-profile:
         condition: service_healthy
      
    networks:
      - gateway_net
      - user-profile_net

volumes:
  user-profile-data:

networks:
  user-profile_net:
  gateway_net: