services:
  user-profile:
    build:
      context: .
      dockerfile: ./services/user_profile/Dockerfile
    container_name: user-profile
    depends_on:
      - user-profile-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@user-profile-db:5432/user_profile_db
      - PYTHONPATH=/app/service/src
    ports:
      - "5001:50051"
    networks:
      - user-profile_net
      - gateway_net
    platform: linux/amd64


  user-profile-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_profile_db
    volumes:
      - user-profile-data:/var/lib/postgresql/data
    networks:
      - user-profile_net
    ports:
      - "5433:5432"
  
  # user-profile-migrations:
  #   build:
  #     context: .
  #     dockerfile: ./services/user_profile_migrations/Dockerfile
  #   depends_on:
  #     - user-profile-db
  #   environment:
  #     - DATABASE_URL=postgresql+psycopg2://user:password@user-profile-db:5432/user_profile_db
  #   networks:
  #     - user-profile_net


  grpc-sandbox:
    build:
      context: .
      dockerfile: ./services/grpc_sandbox/Dockerfile
    container_name: grpc-sandbox
    # depends_on:
    #    - user-profile
         
      
    networks:
      - gateway_net
      - user-profile_net

  application_management:
    build:
      context: .
      dockerfile: ./services/application-management/Dockerfile
    container_name: application-management
    depends_on:
      - application-management-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@application-management-db:5432/application_management_db
      - PYTHONPATH=/app/service/src
    ports:
      - "5002:50052"  
    networks:
      - application_management_net
      - gateway_net

  application-management-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application_management_db
    volumes:
      - user-profile-data:/var/lib/postgresql/data
    networks:
      - application_management_net
    ports:
      - "5434:5435"

volumes:
  user-profile-data:

networks:
  user-profile_net:
  gateway_net:
  application_management_net: