# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import notifications_pb2 as notifications_dot_notifications__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notifications/notifications_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNotifications = channel.unary_unary(
                '/src.protos.notifications.NotificationsService/GetNotifications',
                request_serializer=notifications_dot_notifications__pb2.GetNotificationsRequest.SerializeToString,
                response_deserializer=notifications_dot_notifications__pb2.GetNotificationsResponse.FromString,
                _registered_method=True)
        self.MarkAsRead = channel.unary_unary(
                '/src.protos.notifications.NotificationsService/MarkAsRead',
                request_serializer=notifications_dot_notifications__pb2.MarkAsReadRequest.SerializeToString,
                response_deserializer=notifications_dot_notifications__pb2.MarkAsReadResponse.FromString,
                _registered_method=True)
        self.CreateNotification = channel.unary_unary(
                '/src.protos.notifications.NotificationsService/CreateNotification',
                request_serializer=notifications_dot_notifications__pb2.CreateNotificationRequest.SerializeToString,
                response_deserializer=notifications_dot_notifications__pb2.CreateNotificationResponse.FromString,
                _registered_method=True)


class NotificationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAsRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotifications,
                    request_deserializer=notifications_dot_notifications__pb2.GetNotificationsRequest.FromString,
                    response_serializer=notifications_dot_notifications__pb2.GetNotificationsResponse.SerializeToString,
            ),
            'MarkAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAsRead,
                    request_deserializer=notifications_dot_notifications__pb2.MarkAsReadRequest.FromString,
                    response_serializer=notifications_dot_notifications__pb2.MarkAsReadResponse.SerializeToString,
            ),
            'CreateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotification,
                    request_deserializer=notifications_dot_notifications__pb2.CreateNotificationRequest.FromString,
                    response_serializer=notifications_dot_notifications__pb2.CreateNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.protos.notifications.NotificationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.protos.notifications.NotificationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.notifications.NotificationsService/GetNotifications',
            notifications_dot_notifications__pb2.GetNotificationsRequest.SerializeToString,
            notifications_dot_notifications__pb2.GetNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.notifications.NotificationsService/MarkAsRead',
            notifications_dot_notifications__pb2.MarkAsReadRequest.SerializeToString,
            notifications_dot_notifications__pb2.MarkAsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.notifications.NotificationsService/CreateNotification',
            notifications_dot_notifications__pb2.CreateNotificationRequest.SerializeToString,
            notifications_dot_notifications__pb2.CreateNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
