# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from application_management import application_management_pb2 as application__management_dot_application__management__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in application_management/application_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApplicationManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateApplication = channel.unary_unary(
                '/src.protos.application_management.ApplicationManagementService/CreateApplication',
                request_serializer=application__management_dot_application__management__pb2.CreateApplicationRequest.SerializeToString,
                response_deserializer=application__management_dot_application__management__pb2.ApplicationResponse.FromString,
                _registered_method=True)
        self.GetApplicationByUser = channel.unary_stream(
                '/src.protos.application_management.ApplicationManagementService/GetApplicationByUser',
                request_serializer=application__management_dot_application__management__pb2.GetApplicationRequest.SerializeToString,
                response_deserializer=application__management_dot_application__management__pb2.Application.FromString,
                _registered_method=True)
        self.UpdateApplication = channel.unary_unary(
                '/src.protos.application_management.ApplicationManagementService/UpdateApplication',
                request_serializer=application__management_dot_application__management__pb2.UpdateApplicationRequest.SerializeToString,
                response_deserializer=application__management_dot_application__management__pb2.ApplicationResponse.FromString,
                _registered_method=True)
        self.CancelApplication = channel.unary_unary(
                '/src.protos.application_management.ApplicationManagementService/CancelApplication',
                request_serializer=application__management_dot_application__management__pb2.ApplicationRequest.SerializeToString,
                response_deserializer=application__management_dot_application__management__pb2.ApplicationResponse.FromString,
                _registered_method=True)


class ApplicationManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApplicationByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApplicationManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApplication,
                    request_deserializer=application__management_dot_application__management__pb2.CreateApplicationRequest.FromString,
                    response_serializer=application__management_dot_application__management__pb2.ApplicationResponse.SerializeToString,
            ),
            'GetApplicationByUser': grpc.unary_stream_rpc_method_handler(
                    servicer.GetApplicationByUser,
                    request_deserializer=application__management_dot_application__management__pb2.GetApplicationRequest.FromString,
                    response_serializer=application__management_dot_application__management__pb2.Application.SerializeToString,
            ),
            'UpdateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApplication,
                    request_deserializer=application__management_dot_application__management__pb2.UpdateApplicationRequest.FromString,
                    response_serializer=application__management_dot_application__management__pb2.ApplicationResponse.SerializeToString,
            ),
            'CancelApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelApplication,
                    request_deserializer=application__management_dot_application__management__pb2.ApplicationRequest.FromString,
                    response_serializer=application__management_dot_application__management__pb2.ApplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.protos.application_management.ApplicationManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.protos.application_management.ApplicationManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApplicationManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.application_management.ApplicationManagementService/CreateApplication',
            application__management_dot_application__management__pb2.CreateApplicationRequest.SerializeToString,
            application__management_dot_application__management__pb2.ApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApplicationByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/src.protos.application_management.ApplicationManagementService/GetApplicationByUser',
            application__management_dot_application__management__pb2.GetApplicationRequest.SerializeToString,
            application__management_dot_application__management__pb2.Application.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.application_management.ApplicationManagementService/UpdateApplication',
            application__management_dot_application__management__pb2.UpdateApplicationRequest.SerializeToString,
            application__management_dot_application__management__pb2.ApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.application_management.ApplicationManagementService/CancelApplication',
            application__management_dot_application__management__pb2.ApplicationRequest.SerializeToString,
            application__management_dot_application__management__pb2.ApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
