"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    BLOOD_TYPE_FIELD_NUMBER: builtins.int
    APPLICATION_TIME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    blood_type: builtins.str
    description: builtins.str
    status: builtins.str
    @property
    def application_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        blood_type: builtins.str = ...,
        application_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        description: builtins.str = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["application_time", b"application_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["application_time", b"application_time", "blood_type", b"blood_type", "description", b"description", "status", b"status", "user_id", b"user_id"]) -> None: ...

global___CreateApplicationRequest = CreateApplicationRequest

@typing.final
class GetApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___GetApplicationRequest = GetApplicationRequest

@typing.final
class UpdateApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_TIME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    BLOOD_TYPE_FIELD_NUMBER: builtins.int
    application_id: builtins.int
    description: builtins.str
    blood_type: builtins.str
    @property
    def application_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        application_id: builtins.int = ...,
        application_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        description: builtins.str = ...,
        blood_type: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["application_time", b"application_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["application_id", b"application_id", "application_time", b"application_time", "blood_type", b"blood_type", "description", b"description"]) -> None: ...

global___UpdateApplicationRequest = UpdateApplicationRequest

@typing.final
class ApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    application_id: builtins.int
    def __init__(
        self,
        *,
        application_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["application_id", b"application_id"]) -> None: ...

global___ApplicationRequest = ApplicationRequest

@typing.final
class ApplicationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    application_id: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        application_id: builtins.int = ...,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["application_id", b"application_id", "message", b"message", "success", b"success"]) -> None: ...

global___ApplicationResponse = ApplicationResponse

@typing.final
class Application(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    BLOOD_TYPE_FIELD_NUMBER: builtins.int
    APPLICATION_TIME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    application_id: builtins.int
    user_id: builtins.int
    blood_type: builtins.str
    status: builtins.str
    description: builtins.str
    @property
    def application_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        application_id: builtins.int = ...,
        user_id: builtins.int = ...,
        blood_type: builtins.str = ...,
        application_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        status: builtins.str = ...,
        description: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["application_time", b"application_time", "created_at", b"created_at", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["application_id", b"application_id", "application_time", b"application_time", "blood_type", b"blood_type", "created_at", b"created_at", "description", b"description", "status", b"status", "updated_at", b"updated_at", "user_id", b"user_id"]) -> None: ...

global___Application = Application
