# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oauth/oauth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oauth/oauth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11oauth/oauth.proto\x12\x10src.protos.oauth\"X\n\x13GoogleSignInRequest\x12\x10\n\x08id_token\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\navatar_url\x18\x04 \x01(\t\"\xbc\x01\n\x14GoogleSignInResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x12\n\navatar_url\x18\x06 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x07 \x01(\t\x12\x15\n\rrefresh_token\x18\x08 \x01(\t\x12\x13\n\x0bis_new_user\x18\t \x01(\x08\x32m\n\x0cOAuthService\x12]\n\x0cGoogleSignIn\x12%.src.protos.oauth.GoogleSignInRequest\x1a&.src.protos.oauth.GoogleSignInResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oauth.oauth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOOGLESIGNINREQUEST']._serialized_start=39
  _globals['_GOOGLESIGNINREQUEST']._serialized_end=127
  _globals['_GOOGLESIGNINRESPONSE']._serialized_start=130
  _globals['_GOOGLESIGNINRESPONSE']._serialized_end=318
  _globals['_OAUTHSERVICE']._serialized_start=320
  _globals['_OAUTHSERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
