syntax = "proto3";

package src.protos.application_management;

import "google/protobuf/timestamp.proto";

service ApplicationManagementService {
  rpc CreateApplication(CreateApplicationRequest) returns (Application);
  rpc GetApplicationByUser (GetApplicationRequest) returns (stream Application);
  rpc UpdateApplication (UpdateApplicationRequest) returns (Application);
  rpc CancelApplication (ApplicationRequest) returns (ApplicationResponse);
  rpc DeleteApplication (ApplicationRequest) returns (ApplicationResponse);
}

message CreateApplicationRequest {
    int64 user_id = 1;
    string blood_type = 2;
    google.protobuf.Timestamp application_time = 3;
    string description = 4;
    string status = 5;
}

message GetApplicationRequest {
    int64 user_id = 1;
}

message UpdateApplicationRequest {
    int64 application_id = 1;
    google.protobuf.Timestamp application_time = 2;
    string description = 3;
    string blood_type = 4;
}

message ApplicationRequest {
    int64 application_id = 1;
}

message ApplicationResponse {
    bool success = 1;
    string message = 2;
}

message Application {
    int64 application_id = 1;
    int64 user_id = 2;
    string blood_type = 3;
    google.protobuf.Timestamp application_time = 4;
    string status = 5;
    string description = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}