"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _UserRole:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UserRoleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UserRole.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _UserRole.ValueType  # 0
    DONOR: _UserRole.ValueType  # 1
    DOCTOR: _UserRole.ValueType  # 2
    ADMIN: _UserRole.ValueType  # 3

class UserRole(_UserRole, metaclass=_UserRoleEnumTypeWrapper): ...

UNKNOWN: UserRole.ValueType  # 0
DONOR: UserRole.ValueType  # 1
DOCTOR: UserRole.ValueType  # 2
ADMIN: UserRole.ValueType  # 3
global___UserRole = UserRole

@typing.final
class DeleteProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___DeleteProfileRequest = DeleteProfileRequest

@typing.final
class DeleteProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___DeleteProfileResponse = DeleteProfileResponse

@typing.final
class GetProfileRequestByEmail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    email: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email"]) -> None: ...

global___GetProfileRequestByEmail = GetProfileRequestByEmail

@typing.final
class CreateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FULL_NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    full_name: builtins.str
    email: builtins.str
    phone: builtins.str
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___UserRole.ValueType]: ...
    def __init__(
        self,
        *,
        full_name: builtins.str = ...,
        email: builtins.str = ...,
        phone: builtins.str = ...,
        roles: collections.abc.Iterable[global___UserRole.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "full_name", b"full_name", "phone", b"phone", "roles", b"roles"]) -> None: ...

global___CreateProfileRequest = CreateProfileRequest

@typing.final
class GetProfileRequestById(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___GetProfileRequestById = GetProfileRequestById

@typing.final
class GetProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    FULL_NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    IS_VERIFIED_FIELD_NUMBER: builtins.int
    REGISTERED_AT_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    full_name: builtins.str
    email: builtins.str
    phone: builtins.str
    avatar_url: builtins.str
    is_verified: builtins.bool
    role: global___UserRole.ValueType
    @property
    def registered_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        full_name: builtins.str = ...,
        email: builtins.str = ...,
        phone: builtins.str = ...,
        avatar_url: builtins.str = ...,
        is_verified: builtins.bool = ...,
        registered_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        role: global___UserRole.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["registered_at", b"registered_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["avatar_url", b"avatar_url", "email", b"email", "full_name", b"full_name", "is_verified", b"is_verified", "phone", b"phone", "registered_at", b"registered_at", "role", b"role", "user_id", b"user_id"]) -> None: ...

global___GetProfileResponse = GetProfileResponse

@typing.final
class UpdateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    FULL_NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    BLOOD_TYPE_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    IS_VERIFIED_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    IS_BANNED_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    full_name: builtins.str
    email: builtins.str
    blood_type: builtins.str
    is_verified: builtins.bool
    is_active: builtins.bool
    is_banned: builtins.bool
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___UserRole.ValueType]: ...
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        full_name: builtins.str = ...,
        email: builtins.str = ...,
        blood_type: builtins.str = ...,
        roles: collections.abc.Iterable[global___UserRole.ValueType] | None = ...,
        is_verified: builtins.bool = ...,
        is_active: builtins.bool = ...,
        is_banned: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blood_type", b"blood_type", "email", b"email", "full_name", b"full_name", "is_active", b"is_active", "is_banned", b"is_banned", "is_verified", b"is_verified", "roles", b"roles", "user_id", b"user_id"]) -> None: ...

global___UpdateProfileRequest = UpdateProfileRequest

@typing.final
class UpdateProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___UpdateProfileResponse = UpdateProfileResponse

@typing.final
class UserProfile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    FULL_NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    BLOOD_TYPE_FIELD_NUMBER: builtins.int
    IS_VERIFIED_FIELD_NUMBER: builtins.int
    TOTAL_DONATIONS_FIELD_NUMBER: builtins.int
    LAST_DONATION_AT_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    IS_BANNED_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    full_name: builtins.str
    email: builtins.str
    blood_type: builtins.str
    is_verified: builtins.bool
    total_donations: builtins.int
    is_active: builtins.bool
    is_banned: builtins.bool
    @property
    def last_donation_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___UserRole.ValueType]: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        full_name: builtins.str = ...,
        email: builtins.str = ...,
        blood_type: builtins.str = ...,
        is_verified: builtins.bool = ...,
        total_donations: builtins.int = ...,
        last_donation_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        roles: collections.abc.Iterable[global___UserRole.ValueType] | None = ...,
        is_active: builtins.bool = ...,
        is_banned: builtins.bool = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at", "last_donation_at", b"last_donation_at", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["blood_type", b"blood_type", "created_at", b"created_at", "email", b"email", "full_name", b"full_name", "is_active", b"is_active", "is_banned", b"is_banned", "is_verified", b"is_verified", "last_donation_at", b"last_donation_at", "roles", b"roles", "total_donations", b"total_donations", "updated_at", b"updated_at", "user_id", b"user_id"]) -> None: ...

global___UserProfile = UserProfile
