# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/user-profile.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'user/user-profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17user/user-profile.proto\x12\x0cuser_profile\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n\x11GetProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"\xd3\x01\n\x12GetProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x12\n\navatar_url\x18\x05 \x01(\t\x12\x13\n\x0bis_verified\x18\x06 \x01(\x08\x12\x31\n\rregistered_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x04role\x18\x08 \x01(\x0e\x32\x16.user_profile.UserRole\"g\n\x14UpdateProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x12\n\navatar_url\x18\x05 \x01(\t\"9\n\x15UpdateProfileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*9\n\x08UserRole\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x44ONOR\x10\x01\x12\n\n\x06\x44OCTOR\x10\x02\x12\t\n\x05\x41\x44MIN\x10\x03\x32\xbf\x01\n\x12UserProfileService\x12O\n\nGetProfile\x12\x1f.user_profile.GetProfileRequest\x1a .user_profile.GetProfileResponse\x12X\n\rUpdateProfile\x12\".user_profile.UpdateProfileRequest\x1a#.user_profile.UpdateProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.user_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERROLE']._serialized_start=490
  _globals['_USERROLE']._serialized_end=547
  _globals['_GETPROFILEREQUEST']._serialized_start=74
  _globals['_GETPROFILEREQUEST']._serialized_end=110
  _globals['_GETPROFILERESPONSE']._serialized_start=113
  _globals['_GETPROFILERESPONSE']._serialized_end=324
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=326
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=429
  _globals['_UPDATEPROFILERESPONSE']._serialized_start=431
  _globals['_UPDATEPROFILERESPONSE']._serialized_end=488
  _globals['_USERPROFILESERVICE']._serialized_start=550
  _globals['_USERPROFILESERVICE']._serialized_end=741
# @@protoc_insertion_point(module_scope)
