"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _UserRole:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UserRoleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UserRole.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _UserRole.ValueType  # 0
    DONOR: _UserRole.ValueType  # 1
    DOCTOR: _UserRole.ValueType  # 2
    ADMIN: _UserRole.ValueType  # 3

class UserRole(_UserRole, metaclass=_UserRoleEnumTypeWrapper): ...

UNKNOWN: UserRole.ValueType  # 0
DONOR: UserRole.ValueType  # 1
DOCTOR: UserRole.ValueType  # 2
ADMIN: UserRole.ValueType  # 3
global___UserRole = UserRole

@typing.final
class GetProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___GetProfileRequest = GetProfileRequest

@typing.final
class GetProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    IS_VERIFIED_FIELD_NUMBER: builtins.int
    REGISTERED_AT_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    name: builtins.str
    email: builtins.str
    phone: builtins.str
    avatar_url: builtins.str
    is_verified: builtins.bool
    role: global___UserRole.ValueType
    @property
    def registered_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        name: builtins.str = ...,
        email: builtins.str = ...,
        phone: builtins.str = ...,
        avatar_url: builtins.str = ...,
        is_verified: builtins.bool = ...,
        registered_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        role: global___UserRole.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["registered_at", b"registered_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["avatar_url", b"avatar_url", "email", b"email", "is_verified", b"is_verified", "name", b"name", "phone", b"phone", "registered_at", b"registered_at", "role", b"role", "user_id", b"user_id"]) -> None: ...

global___GetProfileResponse = GetProfileResponse

@typing.final
class UpdateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    name: builtins.str
    email: builtins.str
    phone: builtins.str
    avatar_url: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        name: builtins.str = ...,
        email: builtins.str = ...,
        phone: builtins.str = ...,
        avatar_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["avatar_url", b"avatar_url", "email", b"email", "name", b"name", "phone", b"phone", "user_id", b"user_id"]) -> None: ...

global___UpdateProfileRequest = UpdateProfileRequest

@typing.final
class UpdateProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___UpdateProfileResponse = UpdateProfileResponse
