syntax = "proto3";

package src.protos.oauth;

service OAuthService {
  rpc GoogleSignIn(GoogleSignInRequest) returns (GoogleSignInResponse);
}

message GoogleSignInRequest {
  string id_token = 1;
  string email = 2;
  string name = 3;
  string avatar_url = 4;
}

message GoogleSignInResponse {
  bool success = 1;
  string message = 2;
  int64 user_id = 3;
  string email = 4;
  string name = 5;
  string avatar_url = 6;
  string access_token = 7;
  string refresh_token = 8;
  bool is_new_user = 9;
}
