# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_profile_pb2 as user_dot_user__profile__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user/user_profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfileById = channel.unary_unary(
                '/src.protos.user.UserProfileService/GetProfileById',
                request_serializer=user_dot_user__profile__pb2.GetProfileRequestById.SerializeToString,
                response_deserializer=user_dot_user__profile__pb2.UserProfile.FromString,
                _registered_method=True)
        self.GetProfileByEmail = channel.unary_unary(
                '/src.protos.user.UserProfileService/GetProfileByEmail',
                request_serializer=user_dot_user__profile__pb2.GetProfileRequestByEmail.SerializeToString,
                response_deserializer=user_dot_user__profile__pb2.UserProfile.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/src.protos.user.UserProfileService/UpdateProfile',
                request_serializer=user_dot_user__profile__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=user_dot_user__profile__pb2.UpdateProfileResponse.FromString,
                _registered_method=True)
        self.CreateProfile = channel.unary_unary(
                '/src.protos.user.UserProfileService/CreateProfile',
                request_serializer=user_dot_user__profile__pb2.CreateProfileRequest.SerializeToString,
                response_deserializer=user_dot_user__profile__pb2.UserProfile.FromString,
                _registered_method=True)
        self.DeleteProfile = channel.unary_unary(
                '/src.protos.user.UserProfileService/DeleteProfile',
                request_serializer=user_dot_user__profile__pb2.DeleteProfileRequest.SerializeToString,
                response_deserializer=user_dot_user__profile__pb2.DeleteProfileResponse.FromString,
                _registered_method=True)


class UserProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProfileById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfileById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileById,
                    request_deserializer=user_dot_user__profile__pb2.GetProfileRequestById.FromString,
                    response_serializer=user_dot_user__profile__pb2.UserProfile.SerializeToString,
            ),
            'GetProfileByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileByEmail,
                    request_deserializer=user_dot_user__profile__pb2.GetProfileRequestByEmail.FromString,
                    response_serializer=user_dot_user__profile__pb2.UserProfile.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=user_dot_user__profile__pb2.UpdateProfileRequest.FromString,
                    response_serializer=user_dot_user__profile__pb2.UpdateProfileResponse.SerializeToString,
            ),
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=user_dot_user__profile__pb2.CreateProfileRequest.FromString,
                    response_serializer=user_dot_user__profile__pb2.UserProfile.SerializeToString,
            ),
            'DeleteProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProfile,
                    request_deserializer=user_dot_user__profile__pb2.DeleteProfileRequest.FromString,
                    response_serializer=user_dot_user__profile__pb2.DeleteProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.protos.user.UserProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.protos.user.UserProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProfileById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.user.UserProfileService/GetProfileById',
            user_dot_user__profile__pb2.GetProfileRequestById.SerializeToString,
            user_dot_user__profile__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfileByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.user.UserProfileService/GetProfileByEmail',
            user_dot_user__profile__pb2.GetProfileRequestByEmail.SerializeToString,
            user_dot_user__profile__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.user.UserProfileService/UpdateProfile',
            user_dot_user__profile__pb2.UpdateProfileRequest.SerializeToString,
            user_dot_user__profile__pb2.UpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.user.UserProfileService/CreateProfile',
            user_dot_user__profile__pb2.CreateProfileRequest.SerializeToString,
            user_dot_user__profile__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.protos.user.UserProfileService/DeleteProfile',
            user_dot_user__profile__pb2.DeleteProfileRequest.SerializeToString,
            user_dot_user__profile__pb2.DeleteProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
