"""add unique constraint on id email phone

Revision ID: f6ce3f313908
Revises: be8646277828
Create Date: 2025-11-05 22:45:05.238674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ce3f313908'
down_revision: Union[str, Sequence[str], None] = 'be8646277828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_users_identity', 'users_', ['id', 'email', 'phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_users_identity', 'users_', type_='unique')
    # ### end Alembic commands ###
